security:
  oauth2:
    client:
      clientID: a7e757298a387b70e44c32a9d1ded7accdbe2c2d469e02acf7e973f6988bbfab
      clientSecret: faac600ab44b9f2c20107eb9ad83b02d3464aef3a389e3ca7ef02ed111208f34
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user
server:
  port: 9950
