spring:
  application:
    name: project
  profiles:
    active: @spring.profiles.active@
server:
  port: ${PORT:9200}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
