image: maven:3.3.9-jdk-8

cache:
    paths:
        - .m2/repository

before_script:
    - cd webserver

after_srcript:
    - cd webserver

stages:
    - build
    - test
    - package
    - publish
    - deploy

#build jobs
UIServer:build:
    stage: build
    script: cd UIServer / && mvn clean compile
    only:
        changes:
            - UIServer/**/*

compiler:build:
    stage: build
    script: cd compiler / && mvn clean compile
    only:
        changes:
            - compiler/**/*

dark-mode:build:
    stage: build
    script: cd dark-mode / && mvn clean compile
    only:
        changes:
            - dark-mode/**/*

discoveryserver:build:
    stage: build
    script: cd discoveryserver / && mvn clean compile
    only:
        changes:
            - discoveryserver/**/*

gateway:build:
    stage: build
    script: cd gateway / && mvn clean compile -P prod
    only:
        changes:
            - gateway/**/*

project:build:
    stage: build
    script: cd project / && mvn clean compile
    only:
        changes:
            - project/**/*


