spring:
  application:
    name: gateway
server:
  port: ${PORT:8000}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
#ribbon.ConnectTimeout: 10000
#ribbon.ReadTimeout: 10000
zuul:
  ignored-services: "*"
  routes:
    darkmode:
      path: "/dark-mode/**"
      service-id: darkmode
      strip-prefix: false
