spring:
  application:
    name: gateway
server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
#ribbon.ConnectTimeout: 10000
#ribbon.ReadTimeout: 10000
zuul:
  ignored-services: "*"
  routes:
    dark-mode-service:
      path: "/dark-mode/**"
      service-id: dark-mode
      strip-prefix: false
    project-service:
      path: "/project/**"
      service-id: project
      strip-prefix: false
    frontend-service:
      path: "/ui/**"
      service-id: ui
      strip-prefix: false
    compiler-service:
      path: "/compiler/**"
      service-id: compiler
      strip-prefix: false
