version: '3.7'
services:
  discovery-service:
    image: gitlab.lrz.de:5005/ase20-group3-2/onlineide/discoveryserver
    restart: on-failure
    ports:
      - 8761:8761
  gateway:
    image: gitlab.lrz.de:5005/ase20-group3-2/onlineide/gateway
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  dark-mode:
    image: gitlab.lrz.de:5005/ase20-group3-2/onlineide/dark-mode
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  ui:
    image: gitlab.lrz.de:5005/ase20-group3-2/onlineide/ui
    restart: on-failure
    ports:
      - 9400:9400
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  compiler:
    image: gitlab.lrz.de:5005/ase20-group3-2/onlineide/compiler
    restart: on-failure
    ports:
      - 7000:7000
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  project:
    image: gitlab.lrz.de:5005/ase20-group3-2/onlineide/project
    restart: on-failure
    depends_on:
      - db
    ports:
      - 9200:9200
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/project_db??user=project_user&password=project_pw
      - POSTGRES_DB=project_db
      - POSTGRES_PASSWORD=project_pw
      - POSTGRES_USER=project_user
      - EUREKA_SERVER=http://discovery-service:8761/eureka
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_PASSWORD=project_pw
      - POSTGRES_USER=project_user
