spring:
  application:
    name: gateway
server:
  port: ${PORT:8080}
security:
  oauth2:
    client:
      clientId: a72a0b32df2d8cd929a0878b593c870d773e2243474fde2dc54ae3a30f82b973
      clientSecret: a408ca259eacac670837aaa1ffc4c72bb55adab39d912ab4634997104dbd7b8a
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
#ribbon.ConnectTimeout: 10000
#ribbon.ReadTimeout: 10000
zuul:
  ignored-services: "*"
  routes:
    dark-mode:
      path: "/dark-mode/**"
      service-id: dark-mode
      strip-prefix: false
    project:
      path: "/project/**"
      service-id: project
      strip-prefix: false
    ui:
      path: "/ui/**"
      service-id: ui
      strip-prefix: false
    compiler:
      path: "/compiler/**"
      service-id: compiler
      strip-prefix: false

